stages:
  - pipeline

build:
  stage: pipeline
  image: archlinux:base-devel
  script:
    - pacman -Syu rustup --noconfirm
    - rustup toolchain install nightly --profile minimal
    - rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - RUSTFLAGS="-Zlocation-detail=none -Zthreads=8" cargo build --target x86_64-unknown-linux-gnu --profile release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
    - time ./target/x86_64-unknown-linux-gnu/release/xf
    - tar -czf xfetch.tar.gz target/x86_64-unknown-linux-gnu/release/xfetch
  artifacts:
    paths:
      - xfetch.tar.gz
    expire_in: 1 week