steps:
  - name: Build
    image: rust:latest
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default stable
      - apt-get update
      - RUSTFLAGS="-Zlocation-detail=none -Zthreads=8" cargo build --target x86_64-unknown-linux-gnu --profile optimized-build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
      - time ./target/x86_64-unknown-linux-gnu/optimized-build/xfetch

  - name: Artifact
    image: python:latest
    commands:
        - pip install requests
        - wget https://codeberg.org/JakobDev/ci-scripts/raw/branch/main/release/codeberg-release-upload.py
        - export CODEBERG_REPO=XDR
        - export CODEBERG_API_TOKEN=$XFETCH_TOKEN
        - python ./codeberg-release-upload.py ./target/x86_64-unknown-linux-gnu/optimized-build/xfetch
    secrets: [xfetch_token]