steps:
  - name: Build
    image: rust:latest
    commands:
      - rustup default nightly
      - rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - apt-get update
      - apt-get install -y time
      - RUSTFLAGS="-Zlocation-detail=none -Zthreads=8" cargo build --target x86_64-unknown-linux-gnu --profile release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort

  - name: Check
    image: ubuntu:latest
    commands:
      - cd target/x86_64-unknown-linux-gnu/release
      - chmod +x xfetch
      - /bin/bash -c "time ./xfetch"