[package]
name = "xfetch"
version = "2.1.3"
edition = "2021"

[dependencies]
tokio = { version = "1.39", features = ["macros", "rt-multi-thread"] }
sysinfo_dot_h = "0.2.1"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true
