name: xCompile_main

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust (nightly)
      uses: actions-rs/toolchain@v1
      with:
            profile: minimal
            toolchain: nightly
            override: true
            components: rust-src

    - name: Build
      run: RUSTFLAGS="-Zlocation-detail=none -Zthreads=8" cargo build --target x86_64-unknown-linux-gnu --profile optimized-build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort
    #- name: Tests
    #  run: cargo test --verbose
    - name: Check
      run: time ./target/x86_64-unknown-linux-gnu/optimized-build/xfetch
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
          name: xfetch
          path: target/x86_64-unknown-linux-gnu/optimized-build/xfetch
